name: home
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  component_library:
    path: ../../component_library
  wallet_repository:
    path: ../../wallet_repository
  domain_models:
    path: ../../domain_models
  converter:
    path: ../../converter
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - ../../../assets/icons/
