name: key_value_storage
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  hive: ^2.2.3
  meta: ^1.8.0
  path_provider: ^2.0.13

dev_dependencies: 
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  lints: ^2.0.1
  test: ^1.23.1
