name: bdk_api
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  bdk_flutter: ^0.27.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3


flutter:
  uses-material-design: true
